### ISSUE TITLE
CacheModuleSetException

### ISSUE THREAD

**Issue by andrewharvey** [jpodwys/superagent-cache-plugin#7]
I'm getting this error, it seems to happen either when running with concurrency.

```
cache-module: .set() failed for cache of type cache-module { name: 'CacheModuleSetException',
  message:
   TypeError: Cannot read property 'value' of undefined
```

I'll try to reduce it down to a minimal poc of the issue, but I thought I'd post the error first in case anyone has seen it before or could explain what it means.

**Comment by andrewharvey** [comment]
Sorry turns out this was an error in my code, the cache-module message thew me off but the stack trace pointed to the right place in the source code where it really was trying to read 'value' of undefined.

**Comment by jpodwys** [comment]
I'm glad you got it worked out! Is there something I can do to make the error message more explicit so debugging this sort of issue would be simpler in the future? I can't get around the fact that the cache module will need to throw an exception since it's the one executing the provided callback, but perhaps changing the wording would be helpful. Or is the stack trace sufficient?
