### ISSUE TITLE
Node process does not terminate

### ISSUE THREAD

**Issue by hottehead** [jpodwys/superagent-cache-plugin#9]
Im currently using this plugin in a typescript project which is run on AWS lambda or within lambda docker container (SAM Tool) locally. When I activate the cache plugin the lambda functions do not terminate anymore. I also tried the superagent call via mocha testing framework. In this case the process does not terminate either, although all testing output is written to the console.

Furthermore it seems as if something worked fine. The items are written to the redis instance, but the lambda functions do not terminate. 

These are the installed versions
``` 
├── typescript@3.3.4000
├── superagent@4.1.0
├── superagent-cache-plugin@2.0.1
├── cache-service-redis@2.0.0
```

I needed to declare modules for them as there are no typings available. Im no typescript expert. So maybe the error is located here.
``` 
# cache-service-redis.ts
declare module 'cache-service-redis';
```

``` 
# superagent-cache-plugin.ts
declare module 'superagent-cache-plugin';
```

This is the setup
``` 
import RedisCache = require('cache-service-redis');
import superagentCache = require('superagent-cache-plugin');
...
const redisConfig = {
    defaultExpiration: 300,
    redisData: {
        hostname: process.env.CacheEndpoint,
        port: 6379,
    },
    type: 'app',
};
const redisCache = new RedisCache(redisConfig);
const cache = superagentCache(redisCache);
const request = superagent.get('...').use(cache)
const response = await request
```

Thanks in advance. I'd really like to solve this issue and use the package. I will happily provide more information when needed  =)

Greetings torsten

**Comment by jpodwys** [comment]
Hi, I'm sorry to hear you're having an issue!

I've never tried using this in a lambda setting before, so I'm uncertain what's preventing the process from terminating. Here are a couple of thoughts.

#### Confirm you're calling `context.succeed`

Judging by the fact that your lambda function exited successfully before adding this library, you probably already know this. Disregard if it's not applicable, but I thought I'd mention it since you didn't call a `context` method in your code snippet.

Based on [a couple](https://aws.amazon.com/blogs/compute/getting-nodejs-and-lambda-to-play-nicely/) of [links](https://stackoverflow.com/questions/37094695/how-should-i-connect-to-a-redis-instance-from-an-aws-lambda-function) I found, it looks like you need to be certain you're calling `context.succeed` (or some `context` method) to tell the lambda function that processing has completed.

#### Swap out `cache-service-redis` for `cache-service-cache-module`

If you're already using `context`, then try this out.

This will not fix the issue because `cache-service-cache-module` is strictly an in-memory cache. However, if you make the swap and your lambda setup no longer hangs, then we know that `cache-service-redis` is to blame and we can go from there.

**Comment by hottehead** [comment]
Hey,

thanks for the quick reply.
I solved the issue by setting **`context.callbackWaitsForEmptyEventLoop = false;`**

I swapped the module for `cache-service-cache-module` and it worked. There must be something within the `cache-service-redis` that emits an event into the Node.js event loop? So I leave this issue open and you can close it as you wish.

Thanks for mentioning the `context.succeed` fact. It led me to the resolution. Though I only used the lambda callbacks so far this was new to me. I found [this](https://gist.github.com/hassy/eaea5a958067211f2fed02ead13c2678) and it seems that `context.succeed` and `callback()` are substitutes but not completely equal unless you set the `callbackWaitsForEmptyEventLoop` property.

**Comment by jpodwys** [comment]
I'm glad you found a solution! I'd love to be able to update the readme for lambda users. Based on your success, does this snippet look correct?

```js
exports.handler = function (event, context, callback) {
  superagent
    .get(uri)
    .use(superagentCache)
    .end(function (err, response){
      // handle response here
      // terminate process with `context`
      return context.succeed();
      // OR terminate process with `callback`
      context.callbackWaitsForEmptyEventLoop = false;
      return callback(null);
    }
  );
};
```

If this looks wrong, please correct me. If you'd like contributor credit for finding this solution, would you mind making a PR to the readme in this repo or `cache-service-redis`? If not, I can update them.

Thanks again!

**Comment by hottehead** [comment]
Your snippet looks correct to me. Thanks for leaving the credit =) I made a PR in `cache-service-redis`  repository.
